title: Marti Ritter # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Biophysicist with 3 years of experience working in Neuroscience and extensive contact and diverse work in Data Science.
  Currently working as a freelancer while simultaneously finishing first publication on innate threat perception.
  Attained a master's degree in Biophysics from the Humboldt-Universität zu Berlin at the end of 2020.
  <br>
  Multiple projects involving the analysis of text and video data, as well as synchronized time series.
  Most recent work included the coordination of a small group of researchers in a novel project, the development and implementation 
  of a multi-component behavioral research setup, and the creation of an automated processor for the generation 
  of legally required documentation.
  <br><br>

  <a href="https://linkedin.com/in/marti-ritter/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
