title: Marti Ritter # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Highly motivated Data Scientist with 6+ years of experience in neuroscience and preclinical research.
  Certified Professional Scrum Master with a proven ability to lead projects, automate processes, and deliver actionable data-driven insights in academic and industry settings. 
  <br><br>
  Seeks challenging and innovative projects where skills can be leveraged to drive impactful results and to collaborate effectively.
  <br><br>
  <a href="https://linkedin.com/in/marti-ritter/">View My LinkedIn Profile</a> 
  
github:
  is_project_page: false
  is_user_page: false
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
