title: Marti Ritter # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Research assistant working since 2 years in neuroscience. Obtained a master's degree in biophysics at the end of 2020.
  Currently coordinating a project on innate fear perception in mice while working as a freelance programmer.
  Interests include neuroscience, data science and programming. 
  <br><br>

  <a href="https://linkedin.com/in/marti-ritter/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
