title: Marti Ritter # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Biophysicist with 3 years of experience working in Neuroscience and diverse projects in Data Science.
  Working as a freelancer while simultaneously finishing first publication on innate threat perception.
  Attained a master's degree in Biophysics from the Humboldt-Universität zu Berlin at the end of 2020.
  <br><br>
  Experienced in analysis of text, video data, and synchronized time series.
  Coordinated a group of researchers in a novel project, developed and implemented a complex 
  behavioral research setup, created an automated processor for legally required documentation.
  <br><br>

  <a href="https://linkedin.com/in/marti-ritter/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
