title: Marti Ritter # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist with 6 years of experience working in Neuroscience and pre-clinical research.
  First 3 years in a diverse academic environment, next 3 years in pre-clinical industry setting investigating complex behavioral data to support fingerprinting efforts.
  Planned and implemented a wide range of projects, research topics including innate fear, social behavior, behavior segmentation.
  <br><br>
  
  Certified Professional Scrum Master with first experience leading a small team during novel research project, facilitating teams with Data Science, delivering valuable insights into complex datasets.
  Experienced in analysis of text & video data, synchronized time series, multi-dimensional behavioral recordings.
  <br><br>

  <a href="https://linkedin.com/in/marti-ritter/">View My LinkedIn Profile</a> 
  
github:
  is_project_page: false
  is_user_page: true
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
